name: Setup env
description: composite action to setup env

runs:
  using: composite
  steps:
    - uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
    - uses: arduino/setup-task@v2
    - uses: gacts/install-hurl@v1

    # for sampleapp
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - uses: pnpm/action-setup@v4
      with:
        version: '9'
