// Code generated by MockGen. DO NOT EDIT.
// Source: main.go
//
// Generated by this command:
//
//	mockgen -source=main.go -destination=mock.go -package=enginectl
//

// Package enginectl is a generated GoMock package.
package enginectl

import (
	reflect "reflect"

	model "github.com/enuesaa/cywagon/internal/service/model"
	gomock "go.uber.org/mock/gomock"
)

// MockEngineInterface is a mock of EngineInterface interface.
type MockEngineInterface struct {
	ctrl     *gomock.Controller
	recorder *MockEngineInterfaceMockRecorder
	isgomock struct{}
}

// MockEngineInterfaceMockRecorder is the mock recorder for MockEngineInterface.
type MockEngineInterfaceMockRecorder struct {
	mock *MockEngineInterface
}

// NewMockEngineInterface creates a new mock instance.
func NewMockEngineInterface(ctrl *gomock.Controller) *MockEngineInterface {
	mock := &MockEngineInterface{ctrl: ctrl}
	mock.recorder = &MockEngineInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEngineInterface) EXPECT() *MockEngineInterfaceMockRecorder {
	return m.recorder
}

// PrintBanner mocks base method.
func (m *MockEngineInterface) PrintBanner(confs []model.Conf) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintBanner", confs)
}

// PrintBanner indicates an expected call of PrintBanner.
func (mr *MockEngineInterfaceMockRecorder) PrintBanner(confs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintBanner", reflect.TypeOf((*MockEngineInterface)(nil).PrintBanner), confs)
}

// Serve mocks base method.
func (m *MockEngineInterface) Serve(confs []model.Conf) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Serve", confs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Serve indicates an expected call of Serve.
func (mr *MockEngineInterfaceMockRecorder) Serve(confs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Serve", reflect.TypeOf((*MockEngineInterface)(nil).Serve), confs)
}

// StartHealthCheck mocks base method.
func (m *MockEngineInterface) StartHealthCheck(confs []model.Conf) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartHealthCheck", confs)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartHealthCheck indicates an expected call of StartHealthCheck.
func (mr *MockEngineInterfaceMockRecorder) StartHealthCheck(confs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartHealthCheck", reflect.TypeOf((*MockEngineInterface)(nil).StartHealthCheck), confs)
}

// StartUp mocks base method.
func (m *MockEngineInterface) StartUp(confs []model.Conf) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartUp", confs)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartUp indicates an expected call of StartUp.
func (mr *MockEngineInterfaceMockRecorder) StartUp(confs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartUp", reflect.TypeOf((*MockEngineInterface)(nil).StartUp), confs)
}

// ValidateConfs mocks base method.
func (m *MockEngineInterface) ValidateConfs(confs []model.Conf) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateConfs", confs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateConfs indicates an expected call of ValidateConfs.
func (mr *MockEngineInterfaceMockRecorder) ValidateConfs(confs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateConfs", reflect.TypeOf((*MockEngineInterface)(nil).ValidateConfs), confs)
}
