// Code generated by MockGen. DO NOT EDIT.
// Source: main.go
//
// Generated by this command:
//
//	mockgen -source=main.go -destination=mock.go -package=enginectl
//

// Package enginectl is a generated GoMock package.
package enginectl

import (
	reflect "reflect"

	model "github.com/enuesaa/cywagon/internal/service/model"
	gomock "go.uber.org/mock/gomock"
)

// MockEngineInterface is a mock of EngineInterface interface.
type MockEngineInterface struct {
	ctrl     *gomock.Controller
	recorder *MockEngineInterfaceMockRecorder
	isgomock struct{}
}

// MockEngineInterfaceMockRecorder is the mock recorder for MockEngineInterface.
type MockEngineInterfaceMockRecorder struct {
	mock *MockEngineInterface
}

// NewMockEngineInterface creates a new mock instance.
func NewMockEngineInterface(ctrl *gomock.Controller) *MockEngineInterface {
	mock := &MockEngineInterface{ctrl: ctrl}
	mock.recorder = &MockEngineInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEngineInterface) EXPECT() *MockEngineInterfaceMockRecorder {
	return m.recorder
}

// Deploy mocks base method.
func (m *MockEngineInterface) Deploy(sitename, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deploy", sitename, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deploy indicates an expected call of Deploy.
func (mr *MockEngineInterfaceMockRecorder) Deploy(sitename, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deploy", reflect.TypeOf((*MockEngineInterface)(nil).Deploy), sitename, path)
}

// PrintBanner mocks base method.
func (m *MockEngineInterface) PrintBanner(confs []model.Conf) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintBanner", confs)
}

// PrintBanner indicates an expected call of PrintBanner.
func (mr *MockEngineInterfaceMockRecorder) PrintBanner(confs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintBanner", reflect.TypeOf((*MockEngineInterface)(nil).PrintBanner), confs)
}

// Read mocks base method.
func (m *MockEngineInterface) Read(sitename string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", sitename)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockEngineInterfaceMockRecorder) Read(sitename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockEngineInterface)(nil).Read), sitename)
}

// SendSock mocks base method.
func (m *MockEngineInterface) SendSock() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendSock")
	ret0, _ := ret[0].(error)
	return ret0
}

// SendSock indicates an expected call of SendSock.
func (mr *MockEngineInterfaceMockRecorder) SendSock() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendSock", reflect.TypeOf((*MockEngineInterface)(nil).SendSock))
}

// Serve mocks base method.
func (m *MockEngineInterface) Serve(confs []model.Conf) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Serve", confs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Serve indicates an expected call of Serve.
func (mr *MockEngineInterfaceMockRecorder) Serve(confs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Serve", reflect.TypeOf((*MockEngineInterface)(nil).Serve), confs)
}

// StartListenSock mocks base method.
func (m *MockEngineInterface) StartListenSock() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartListenSock")
	ret0, _ := ret[0].(error)
	return ret0
}

// StartListenSock indicates an expected call of StartListenSock.
func (mr *MockEngineInterfaceMockRecorder) StartListenSock() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartListenSock", reflect.TypeOf((*MockEngineInterface)(nil).StartListenSock))
}

// ValidateConfs mocks base method.
func (m *MockEngineInterface) ValidateConfs(confs []model.Conf) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateConfs", confs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateConfs indicates an expected call of ValidateConfs.
func (mr *MockEngineInterfaceMockRecorder) ValidateConfs(confs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateConfs", reflect.TypeOf((*MockEngineInterface)(nil).ValidateConfs), confs)
}
