// Code generated by MockGen. DO NOT EDIT.
// Source: log.go
//
// Generated by this command:
//
//	mockgen -source=log.go -destination=log_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package infra

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLogRepositoryInterface is a mock of LogRepositoryInterface interface.
type MockLogRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockLogRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockLogRepositoryInterfaceMockRecorder is the mock recorder for MockLogRepositoryInterface.
type MockLogRepositoryInterfaceMockRecorder struct {
	mock *MockLogRepositoryInterface
}

// NewMockLogRepositoryInterface creates a new mock instance.
func NewMockLogRepositoryInterface(ctrl *gomock.Controller) *MockLogRepositoryInterface {
	mock := &MockLogRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockLogRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogRepositoryInterface) EXPECT() *MockLogRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Info mocks base method.
func (m *MockLogRepositoryInterface) Info(format string, a ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a_2 := range a {
		varargs = append(varargs, a_2)
	}
	ret := m.ctrl.Call(m, "Info", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Info indicates an expected call of Info.
func (mr *MockLogRepositoryInterfaceMockRecorder) Info(format any, a ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, a...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogRepositoryInterface)(nil).Info), varargs...)
}
