// Code generated by MockGen. DO NOT EDIT.
// Source: conf.go
//
// Generated by this command:
//
//	mockgen -source=conf.go -destination=conf_mock.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	model "github.com/enuesaa/cywagon/internal/service/model"
	gomock "go.uber.org/mock/gomock"
)

// MockConfSrvInterface is a mock of ConfSrvInterface interface.
type MockConfSrvInterface struct {
	ctrl     *gomock.Controller
	recorder *MockConfSrvInterfaceMockRecorder
	isgomock struct{}
}

// MockConfSrvInterfaceMockRecorder is the mock recorder for MockConfSrvInterface.
type MockConfSrvInterfaceMockRecorder struct {
	mock *MockConfSrvInterface
}

// NewMockConfSrvInterface creates a new mock instance.
func NewMockConfSrvInterface(ctrl *gomock.Controller) *MockConfSrvInterface {
	mock := &MockConfSrvInterface{ctrl: ctrl}
	mock.recorder = &MockConfSrvInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfSrvInterface) EXPECT() *MockConfSrvInterfaceMockRecorder {
	return m.recorder
}

// IsConfPath mocks base method.
func (m *MockConfSrvInterface) IsConfPath(path string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsConfPath", path)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsConfPath indicates an expected call of IsConfPath.
func (mr *MockConfSrvInterfaceMockRecorder) IsConfPath(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsConfPath", reflect.TypeOf((*MockConfSrvInterface)(nil).IsConfPath), path)
}

// List mocks base method.
func (m *MockConfSrvInterface) List(search []string) ([]model.Conf, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", search)
	ret0, _ := ret[0].([]model.Conf)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockConfSrvInterfaceMockRecorder) List(search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockConfSrvInterface)(nil).List), search)
}

// ListConfPaths mocks base method.
func (m *MockConfSrvInterface) ListConfPaths(search []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConfPaths", search)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConfPaths indicates an expected call of ListConfPaths.
func (mr *MockConfSrvInterfaceMockRecorder) ListConfPaths(search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConfPaths", reflect.TypeOf((*MockConfSrvInterface)(nil).ListConfPaths), search)
}

// Read mocks base method.
func (m *MockConfSrvInterface) Read(path string) (model.Conf, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", path)
	ret0, _ := ret[0].(model.Conf)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockConfSrvInterfaceMockRecorder) Read(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockConfSrvInterface)(nil).Read), path)
}

// Validate mocks base method.
func (m *MockConfSrvInterface) Validate(conf model.Conf) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", conf)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockConfSrvInterfaceMockRecorder) Validate(conf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockConfSrvInterface)(nil).Validate), conf)
}
