name: ansiblecheck

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ansiblecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/env
      - run: pip install ansible
  
      - working-directory: ./examples/ansible
        run: ansible-playbook playbook.yml
