name: ci

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - run: go install

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - run: go test ./...

  staticcheck:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - run: echo '# staticcheck' >> $GITHUB_STEP_SUMMARY
      - run: staticcheck ./... >> $GITHUB_STEP_SUMMARY
  
  ansiblecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install ansible
  
      - working-directory: ./ansible
        run: ansible-playbook --check playbook.yml
