name: ci

on:
  push:
    branches:
      - '**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - run: go test ./...
      - run: go install
