name: e2e

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/env

      # for sampleapp
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - uses: pnpm/action-setup@v4
        with:
          version: '9'
      # hurl
      - uses: gacts/install-hurl@v1

      - run: go install

      - run: pnpm install
        working-directory: ./testdata/sampleapp
      - run: pnpm build
        working-directory: ./testdata/sampleapp

      - run: cywagon -help

      - run: nohup cywagon up testdata/sampleapp &
      - run: hurl --test testdata/sampleapp
